use_frameworks!

platform :ios, '10.0'

target 'ZPJsonPreview_Example' do
  pod 'ZPJsonPreview', :path => '../'

  target 'ZPJsonPreview_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
