#use_frameworks!

platform :ios, '10.0'
#install! 'cocoapods', :disable_input_output_paths => true

target 'ZPJsonPreview_Example' do
  pod 'ZPJsonPreview', :path => '../'

  target 'ZPJsonPreview_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
